/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include <stdint.h>
#define ADC_BASE_ADDR 		0x40012000UL
#define ADC_CR1_REG_OFFSET 	0x04UL
#define ADC_CR1_REG_ADDR	(ADC_BASE_ADDR+ADC_CR1_REG_OFFSET)
#define RCC_BASE_ADDR 		0x40023800UL
#define RCC_APB2_ENR_OFFSET 0x44UL
#define RCC_BASE_ENR_ADDR	(RCC_BASE_ADDR+RCC_APB2_ENR_OFFSET)
int main(void)
{
	//
   uint32_t *pAdcCtrlreg = (uint32_t*) ADC_CR1_REG_ADDR;
   uint32_t *pRccApb2enr = (uint32_t*) RCC_BASE_ENR_ADDR;
   //enable the peripheral clock for ADC
   *pRccApb2enr |= (1<< 8);
   //modify the ADC cr1 register
   *pAdcCtrlreg |= (1 << 8);
	for(;;);
}
